Fix ordering of SUSE modules
The A-Z ordering breaks the registration task:

```bash
Error: Registration server returned 'The product you are attempting to activate (Public Cloud Module 15 SP4 x86_64) requires one of these products to be activated first: Server Applications Module 15 SP4 x86_64' (422)
```